name: Trigger Draw QMK Workflow

on:
  workflow_run:
    workflows:
      - Build QMK firmware
    types:
      - completed

jobs:
  trigger-draw:
    name: Trigger Draw QMK Workflow
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Call Draw QMK Workflow
        uses: ./.github/workflows/draw-zmk.yml
        with:
          keymap_patterns: "keyboards/*/keymap.json"
          config_path: "keymap_drawer.config.yaml"
          output_folder: "docs/generated"
